apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-skypilot-test-egress-any"
spec:
  endpointSelector:
    matchLabels:
      app: test-api
  egress:
    - toEntities:
        - all