{{ if and (ne "prod" .Release.Namespace) (ne "dev" .Release.Namespace) }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-credentials
  annotations:
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/cluster-credentials
data: {}
{{ end }}