apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-skypilot-db-cnpg-egress-kube-apiserver"
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: skypilot-db
  egress:
    - toEntities:
        - kube-apiserver