apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-cnpg-ingress-skypilot-db-cnpg"
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: skypilot-db
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: cnpg-system
        app.kubernetes.io/name: cloudnative-pg