apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-skypilot-db-cnpg-ingress-cnpg"
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: skypilot-db
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.cilium.k8s.policy.serviceaccount: skypilot-db