apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-skypilot-egress-any"
spec:
  endpointSelector:
    matchLabels:
      app: skypilot-api
  egress:
    - toEntities:
        - all