{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cnpg-skypilot",
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cnpg-skypilot",
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "password": "AgB5O2ygHa3c1eOdg2xbdE5VSSxqB72k2IDxjtaHj8y1IVrlchoQTX89gvyKsLtS1cRbMeTcBYE/IofAzpVwb8zPu2+PZKjsQ2FMyPfh8i0TCEmPbzNfyM37TRMElLGf89jY8g5MPUOxcO4clsEhfZm022wA+rwElsY+aEfgmto97kjtMTdE3xZRAlDoxV2AXsTGgVkWh06sHkBPJzwr58ByDTYEWnZnUxPhCodhnor4VkLF29QClsiOXLreMobbyP39PX1Szpu1pZjrX7zT0+SKn7tKlIf4+dcLbvRF3O4SNeDkwN4vCZI4Z8UTwh3XBOaU6IikoymzmdWvUvsWWh8af/oiaxVSpnXULqaBi9L2IYKteTDJfRWxuY0Ysyb4ba3y4PxvDxSUq20ifyJaS2frDOyeCMhGsjV98NZrX5TLYLYbwpTh9hO8HYB/no98ilh56/sGhkBv4M18EtDVaJMLM+PYtri+37SYZuNEurfOS6ULCGTKUzlnNxfMGzyd5pXqh6lw3HQ/5F2rN2aSucGXK9x3peGwcx5z/9GxIs6465H2LqVP9t2rjY8029/jmbQwdO5ZFpVnTAY6Ywkhcv3SLpXAyVq3VpW9AXbaXvMM7/a4BEbpM7ibB7vN2IXROOKKG1ua01F79B00fnf9Xx6t1HSuRuT99sFSJ1Y9KJakZqED2zfKp8/xMzP9XrLAiCOGmlSkob03vw==",
      "username": "AgCO4OAsQLk/XZMIGDam0TYenomeAG58ftbpOZgGvdwA8YVXZrFfleX3jRzSJz2tfhAl+PRa6NCW6Gh47OUAcVS6h/ILV54N0WHLgthzw/n+W9YeoObM4T4TRikvbQwDFxd30SX6mxp8f/cMolByNtp55WT16CxbfUgXJQ30YHiQ8PYrBQl0L21KuN3Y0GQ4RFl9a9IgXDmBuTjrY+JpN2PdELFacqe1EN3Jr60oephhJxYfBay1oz5tIXVn3T5lLjnCA9rqoumeD3H1NML6e4lwB2FVKTNcTTtD6l63ArBBEpDWx4O6g1p5d6z5EwsaVBmcLYFha78deszVl1NTJ0xKeSgvRGzf2aKeX3cyhzkaeVHaYoGqXrhispJgHsa8xlgi8Nz4rtJp5Mg/bLmWnk8CWW0YFUA0oPiuCH2+Eabi3vTkohXg0V88dThDuUMMclpT766r3lgwQiBELQ9G2883VfJjl9Zncw4cimyMmDE9D+IuUEMaLlxqwA+0ruMX+CbrPfHlwGntyhflCjjl1DIZ63opcwmSoz+Bm7gsCZyR1JZA70ejHb4+LTwJKafID8GhmaY1wXgyyk3KNmGlkFtkgQq4zRRD2GJTvyEm4qMbtN+SuDQ/NV4AAGpVnE1MB7nJRQ7t7zgmkg4H0kht3f9kcaAmX7nY+cDmC/lW5sr9605HU/Mtn91S1VFeWI0I3+3CKFPgDzHWRA=="
    }
  }
}
