{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cnpg-minio-credentials",
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cnpg-minio-credentials",
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "ACCESS_KEY_ID": "AgBm5IKzcb/921yGlnpxi3n2p1RRqOHBko+tfEF39YOAcyMqorm+kB31RajW7ZN10Ykwneyxigyhbe3YeoaJpnnjv5NXdKhme1IaUBPfFlCpHb6xtDGVr1bz/weQGBBzbEQvB3vsASKPjeIPw5b+EZSvCICBICNAanH0Yyr3/xfyFZH/8kVZnzFQCPP6HE5PRQ6LPOISeFYop3G2T/f9S6Y4atATHXpNIhMrm6sqX0eOkdsnl6c74bMf8ucnCPRxMHdPcM80fXGrGURG30JefWmHiR4BC7uTmT0/AF2m+9f1P80PuC7nYkJEJVAWRevHLcAhdDx13s8dbFEk5Kqf/jj44KNrLOSbI7aozlBlhTNTBcXzSM3fQ1XI/+Othpp8EqQt29i72JKVDbc8sqouQOdTzU5A+xsAZ+5XP/LLDMUmn2dLscWEH5BieHtwi5zMny90BSTM50K7Q4uNUEimZh5N53c5pr+iaCQPJAUFx2dpt8RDY0HHmT3ZCSmidp/VnbXjFge3WjASYg3dyqTYysIvCntgySkCSa/TMWSidjwA0qghJIBuNWo2cUJ/shrbHJ+pqNj1xckUNJ5WIOJuxLaXb2SirIzdBchu7dTkdKqxtPdLtbse99lyed6rX6YyqbX0kNVyVlisxPJdGbMeuPoocOkg6PbmGZLFyDsQPxMyufENfDbB+7lEfaW2a47E/pdMIezb",
      "ACCESS_SECRET_KEY": "AgAuMEdMr0//756lox8wxN1DhdJZaR9EgMQWfY7WLPednRFgkEyJQQ4FhMYMMVoIWjMgl3xqheFKafFN13zHSPJlbbWO/NRGrdX96W6N6iUxtYu1phnGwyW7Ixqtd67shMXoc1MNzWVZmRk38TNG0/tQs6DnPC6VfEVBN0A8ENhZC0XfNXQIje+52eMIZUs9DTJUGuSRUbzTNqQrqZchXQvzsjZ/3Fo8KGThW3A0C2fFeNl8o1iewzPjE+eIpLWxCubA/Eh3yru32OShlITl7JpkrZ4AoS5b9EN/WUKy/Xa9tpfBhlsgpSHm0m/zWvGpLlyksIxzW7B9dez/mvm0zmUeVLg7j4R5EzzAbJHkjzrVupNPLdGAlel5XRqf1gjjmgFm6OO0fWXPV7WVZ8LDZXvZM6xqWsBQrHo9ivdQTmBMqbcAlFc10oWCUHYiFC4JAJWT81NEf80dn6TBLkCp2C7ST8BnACyKb/9UPFruZZRV1L7i/v0w2tmmwdwBWilvBirdxnOEyez8JqyskzpOQoMovsjcFbYV1S1CDN0rgmhIGTUn06gsImnluzxBfduSaBxGzH4/y9Zq0ndrpODytym/h+X+NE22UrlUJtRu3+d8YBo0NNjmJQlL971hncMr7DssankOf7sUY92iUNlDqg+xd1n9szhtx0vgXRmT5m9KS40dVKGYQQtujUIUEDqkE6ignQG0Aej70mFIbH3gYFLKZHT/orok"
    }
  }
}
