{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cnpg-skypilot-db",
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cnpg-skypilot-db",
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "password": "AgCbMm0xtNpCiKlOkxIDx4Ea5U3zylVl/fsrA/7KWBHiTmcC5lMMlPeEged6rBqnkf4khIW5du8f2KwnEQysvJJApk+cPN5mubk0j+wvuDxgT0bUaKArevEzqrZwFL2fH2AqlEQW8wmXZtbKSmSmihD1JeWeHcROtzjvyoJKGvDlspIt6jKNXrSAVJoW++sCkH+T1igh0214tM88lUf99jwZYKHKyHUTIp0P0e7Yc8ysx08+D4H3I5e6ZdlwKF4DEefoZjuzn0FJ65yUW/WnnLekbNIMSal6cLHPdyuiKrVfSj55MdUkZA94thj+FboPCWZUufMKAqi/RoxAXJZYo+bSCEJj5ukyZL5ap0AdcNB0Y+XbmwTLJCQYyYNV/tpFTWku60cbtSap4BzM5LTHz25U7IZmmXvm3BYPZ0BBP7gP4V5aRy6VWbJQp/2jW14ri4eI7LOowFGOml8nF4JahA7LuzmbZaRB309Nub4C6dvnKzbu2qwUrbL2TsXzSr526IFNbSjBtJuox6JK8bozn/xpSkFwUNT6GrMuvYRvJkGRIEnF+WvXeOQ6EyiEDP9g1W7Q2LhXhXNgWMuPc3jTNfCtmZPj41Ogte0H+5g1KDsnw60lH/VmhI0tN83R6kQu7lcAKSe9B5tMuacQ2NhU5bUUpzkihM9kgrMeXJrVFQWIR+Vm3/jnNtOXWIhi/NKera2RO6sRRG3JLPxhwA==",
      "username": "AgChwbcJ75Q/Auj5wiG9PnbNVXQtReMpfm2JQ6F5Rkrdb+lh37oSsff0qUPvEGglEoGCRPbzXUWNSdrodo7nfSrmJoEZq9TEKIdu/PlUqXEMmAGGoqtOWOduU27wKWFoBmBRO1lrR6oR0jS8VAoWPmkuAr+T1bzmqNPxSoGAOMTvmLBD+lZxnQ26+WPM9FlU3RINQmng2N14+xSFcI6S/PXEwfcuzkxP9pkXPQynxSvsVdBxf2AhTaPhR9cN/MZ4Q8FyftY2+23ByHTUf/oFQct/0bUb4BU8THaW3x6D7hahJSF3K6i0Z22yN3jPfEAmGRRXiT1OlCR7vi2R95G22VyqdcCZoHE0PhoaKBiZcmwX6gN78G5oqicjH+YcfiR2AUh330nVSLRbp+PLtgIVt7wpziuqxHqtC5kqHkEeao8PB+CZvD7+m8xkXLQCGjLrqreoFjJrDHp6QkTQtBwAdNwIb7aKhx5hQC8+aJVkf2zFLJ++2Mo0EvT4N7DFDMvmxy6Tg9tjROreF8qsKpM8W1JxdALVMiS/rk/whyd5Md7j2uddsI2SI8WTFNQ/ubvyoTHAKn6tAICl7EjFd9dnaOoUVIvR2BNub2Q3YRBtHcYEKNXf/dPrYJuuyJ8WEwqsVZmJ7F2k0YryXPYAYjZYY+maBgwGGhsWOPRSaF9nR6nZzBmseVzS8fbIwU7gfq7Yw3YG7Zvz0tUZxMxDxg=="
    }
  }
}
