{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cnpg-skypilot-db-superuser",
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cnpg-skypilot-db-superuser",
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "password": "AgALMzJYVF6AtqGcsB2PYqeIPYSyRve6qVxiDvp/CzttVpUTbPmPuzonPK6+k0H5LMcceNO0lXZxR+0vSO4reLXWMQgckJpB0pAoBhR0j6+XthKFa8crAvdgDHwXI66Ed/LdVkZfeuO6ZiXOVc3t2VO+IY4Ntb3CN9/aRDGh4a+v1z9focSyXA/gruRS/dX2EJghmMlBh8CIxpHzfhweECzfU4npyDDwvmaewoNfWEEE7KhsBI2DavikXE04j7vOZ9SfHlHYOvK7f5lLFcIaAg9+nXH/summthFI4ocXiZaQh0rVXS6la8LkT8JTpT2hbhpYfuF/q8015bexUuYZZQnqnLrCZMiItaPXdZ3xbSU5FPXiafN1zOIR3V8M2sbfjRYlBkK9bXpLEBZ0za/JXE9G3/6s9SHJ+SpK7IhWcbPXkuF9FrhYvEnLLxy+UvT/mUdzCRAuEaP3yPkT7nAGQEP/xK5DNXMchSZ5pfZvvzsbjn3IsPcRRW2iB1ELhA2ClEgWevfPWDP9rjkAyehOEEnsup6Z+tRQ+/JLhHvxbpLKWJplOra1RpDXV9tMNP8ehiTnE2azkNOKz9TyWGyfO3JWRJAKDd7SZlfJsRtiAoM5INApki4o9ouuHWFVPRwl7UmvzQLl0VDPCwVSO42kUhboWk1smiS4Eu4vH+r5ypuve6dL9Z5tgQ0+6C0eaNTCw4R3csgPEdDARoBo2niFmT8l7mFJxBzbje7QxZYFfOsAdpa9V3HW77uOXLNr",
      "username": "AgC0VyHA8g0UTCysf4ELAjJ+NRLeeK4PKyYK0FgX8L1RL3086fI/daOrKhriRDC/TlHdowdCxzl7MqndyooTlAefM26mhrtpaIwSa/dmS7iOLAA4YaH2XBGQPpv9Q1PXi8mh06ZigvdgJ3n7CMXD4ZBaUuc2Ya4rt2Z1qt9z4ouq0NErRJuUV+EAz906Z4g8vYrmyuhMcLOfUYI1v8VTi8PuCCzmh+pY0ijzgIUaaguvIor2WgxZ3E6n5v3L9H+GpaQOJ8GKxcKAN+ALYpHN6qmPIEi0hcIfhLnRdAl7cx4cZm2dA6mdk7YGoQFm+QhxeyKx4rfIg/Lk/1Hv6mc+ubt2GwmfMwxiTxFCQuXurQLpFbL2A4VSNeXIiXRbXCp2q2QshmZdJDMdoWUmi+wz1TLg1OoBc5rospIgLuc19VD33Vr+BhjXsdrEwkjaw+FNVdkWNRPZpD0latNf7AE29aXGIqHdf6reHYs56OjNUHcmQW21K8F76Fn0fQyQKEGdYDg9MTOx93bMvfpuhbPjKqv+EVV7lwKDOzvOpbaJacPlwRjUir9/KO00Wl6PNQEhBeGoRIEjTR431mhOpPmjYNidvO/fEup/Jvid6WCp1tC0TcXxQf8e5kywURrYlPZjAvCOeHLzc1d2vKUdq/c+XsOYleqhqqNfw/z92XboordWD30iqRq3NBY74vKc7WdumcLVXLY4byILZA=="
    }
  }
}
