{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cnpg-skypilot-db-superuser",
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cnpg-skypilot-db-superuser",
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "password": "AgCdaPvkVjJF/MwPcDY+39gEVbCw8UH04B7f2bdqI2wuQqqBOUkF1mkrIwvgJYnHcBksgA1tsg72rP7ASn0WUbX2/0PGTwwcQW4PdVRTVzahRmPZqiHHNXDp4daV9N4ZuFDvkUX+cMJWB4sh2xJ+ymZBPpTHJXkp1TPBScB4/KdKLjhbWCy5hWsEssQy/rjZwLtogdYnkEXra0SlNu1t0T+5DwuHlxqFcNLf61OBnulAAbGfPe+XHtDjy42AH75EzU6NYorhqta/vTk8NJDZ40iTUMRBoULhylq0ez1foEtkFWXw9cw4tDAIrB9S3lPwXFcZdd2DLm7LYckfZFcTKXv2umJjEci91eCjqGWTsYYNtiCY1yDgAt1pxNEAdGoQi1kmjKmYfhG5tpfsShLck7WYFBSjYV49BcB9yKx+iFWbjYqY0CWro2Qmk2z7lO0ljdcGXUGDx1EvSXZSM5XncZih7Y3mjO2cwoTdQCARg0T9C7LqPPc4vYUwYbQWVDtZOMSFPdKV5q2qJ3+oLuKjVSjEKppX6jN3OEl+FJUphNIKQOcQfO7eWjUjD4eD3FWsAVDMz4KFUAl2bQpReHAt6aoJ/41hmJBTkVoM/WhBpzDNMCZQ76/sbdtCnRhLjOccqglHv1siRXOyANGMlPNJcvHKu44wdefTECc5u+wifpD0dwYYJbXMmzeD95sRlNLJ3t2vJlC6IeNVoJm4O4x7Z84rGi2JaR4Fuq5zCZD6Ub5Q2afm6T9Dy7ip1DMV",
      "username": "AgCJqfZVq66GVq6a7RAhvjyvu//KZoldZH+q1PSZnHPknW5zN49DukuweoPwU6ytRgm+CiDYYMAoYT+WabU51amqiCfKlTFb5I4MJ52s0XNUjtjTN6H1jsdg83bLrapRH51Po0d5Agm/MEvtnn1PKh0eYkqUtDJlYhrQPuZl3UQW/k+G4oAuTNW445zlCgV3O8hnCEYwcU2/ZcmmtO0VydxNs2wTbgyOGMVvy+9lRzVwV/Q32V5GGfixyPGkllRMZhGO7PqUIsjPiLqfXRgjv0F50JnATgS/tG96HWbX+UzH1E3BXaJhLWd8HVCIbvV2dw2eO7kbfU2eXZwQPP33yrr6BsQ46gLrCqD1bHG3jXOk+uJsRBZJTTq9M+BpatHH1i/Gavlfb/XELXs/fUzLFT0scFQSsHSitUpWlSeChq84R/xHMdhSIoXTSZ5WnVJslRFWsu+01msuaLpmBA+NvLRKMGy5gA8KCai46UD9UBPLzpkUNvzQd5cYLmUWUhMAudzg541aOEaEKaoZ84p1OFCYKCBZsqhAIE8EImflF8bEguvr2Axe/U21U5ryUcra+1QQ2RSkkuiE1XAHhJ9XQz39OIHMbkDmTwugxpH37x6gvdRe+FU7XUUSghexbtYBrvbd4MGOVPBZqhBVkb4GsZyiZmJXUQKyWdJl0W2a4cu0kbZIzzJoozBS2u5Nsh8yAt9HQWsKHLC9hA=="
    }
  }
}
