{{ if and (ne "prod" .Release.Namespace) (ne "dev" .Release.Namespace) }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.istio.ingress.prefix }}{{ .Values.istio.ingress.host }}.{{ .Values.istio.ingress.basedomain }}
spec:
  hosts:
  - {{ .Values.istio.ingress.prefix }}{{ .Values.istio.ingress.host }}.{{ .Values.istio.ingress.basedomain }}
  gateways:
  - istio-system/istio-ingressgateway
  - mesh
  http:
    # no timeout for logs
  - match:
    - uri:
        prefix: /jobs/logs
    route:
    - destination:
        host: {{ .Release.Name }}-api-service
  - route:
    - destination:
        host: {{ .Release.Name }}-api-service
    timeout: 30s   
{{ end -}}